-- 코드를 입력하세요
SELECT CART_ID FROM
(SELECT CART_ID, LISTAGG(DISTINCT NAME, ',') WITHIN GROUP (ORDER BY NAME) LIST
FROM CART_PRODUCTS
GROUP BY CART_ID)
WHERE LIST LIKE '%Milk%'
AND LIST LIKE '%Yogurt%'
ORDER BY CART_ID
