-- 코드를 입력하세요
SELECT P.PRODUCT_CODE, SUM(P.PRICE*O.SALES) SALES
FROM PRODUCT P RIGHT JOIN
(
    SELECT PRODUCT_ID, SUM(SALES_AMOUNT) SALES
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID
) O
ON O.PRODUCT_ID=P.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE


-- SELECT PRODUCT_ID, SUM(SALES_AMOUNT) SALES
--     FROM OFFLINE_SALE
--     GROUP BY PRODUCT_ID