-- 코드를 입력하세요
SELECT ANIMAL_ID, NAME FROM
(SELECT I.*, RANK() OVER (
    ORDER BY O.DATETIME - I.DATETIME DESC) RN
FROM ANIMAL_INS I, ANIMAL_OUTS O
WHERE I.ANIMAL_ID = O.ANIMAL_ID)
WHERE RN <= 2
ORDER BY RN