
SELECT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE *30 * (1-P.DISCOUNT_RATE*0.01) FEE
FROM CAR_RENTAL_COMPANY_CAR C,
CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
WHERE C.CAR_TYPE = P.CAR_TYPE
AND C.CAR_ID NOT IN ( SELECT  A.CAR_ID
                      FROM  CAR_RENTAL_COMPANY_CAR              A
                         ,  CAR_RENTAL_COMPANY_RENTAL_HISTORY   B
                     WHERE  A.CAR_ID = B.CAR_ID
                       AND  A.CAR_TYPE IN ('세단', 'SUV')
                       AND  TO_CHAR(B.END_DATE, 'YYYYMMDD') >= '20221101'
                       AND  TO_CHAR(B.START_DATE, 'YYYYMMDD') < '20221201'
    )
AND P.DURATION_TYPE LIKE '30%'
AND C.DAILY_FEE *30* (1-P.DISCOUNT_RATE*0.01) BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC

