# -- 코드를 입력하세요
# SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS, B.SCORE AS SCORE
# FROM REST_INFO A JOIN 
# (SELECT REST_ID, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
# FROM REST_REVIEW
# GROUP BY REST_ID
# ) B
# ON A.REST_ID = B.REST_ID
# WHERE ADDRESS LIKE "%서울%"
# ORDER BY SCORE DESC, FAVORITES DESC;

SELECT REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO JOIN REST_REVIEW USING(REST_ID)
WHERE ADDRESS LIKE '서울%'
GROUP BY REST_ID
ORDER BY SCORE DESC, FAVORITES DESC;
