WITH TWENTY_ONE AS (
SELECT *
FROM USER_INFO 
WHERE TO_CHAR(JOINED,'YYYY')='2021'
    )
    

SELECT EXTRACT(YEAR FROM OS.SALES_DATE) AS YEAR, 
        EXTRACT(MONTH FROM OS.SALES_DATE) AS MONTH, 
        COUNT(DISTINCT(TON.USER_ID)) AS PURCHASED_USERS,
        ROUND(
            COUNT(DISTINCT(TON.USER_ID))/(SELECT COUNT(USER_ID) FROM TWENTY_ONE),1) AS PURCHASED_RATIO
FROM TWENTY_ONE TON INNER JOIN ONLINE_SALE OS 
ON TON.USER_ID = OS.USER_ID
GROUP BY EXTRACT(YEAR FROM OS.SALES_DATE), 
        EXTRACT(MONTH FROM OS.SALES_DATE)        
ORDER BY YEAR, MONTH;