-- 코드를 입력하세요
SELECT B.PRODUCT_ID, B.PRODUCT_NAME, SUM(A.AMOUNT*B.PRICE) TOTAL_SALES
FROM (
    SELECT * FROM FOOD_ORDER
    WHERE TO_CHAR(PRODUCE_DATE, 'YYYYMM') LIKE '202205') A,
    FOOD_PRODUCT B
WHERE A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY B.PRODUCT_ID, B.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, PRODUCT_ID