SELECT H.HISTORY_ID, 
    (1-NVL(P.DISCOUNT_RATE, 0)* 0.01) * H.DAILY_FEE * (H.END_DATE-H.START_DATE+1) AS FEE
FROM
(SELECT H.HISTORY_ID, H.CAR_ID, C.CAR_TYPE, H.END_DATE, H.START_DATE, C.DAILY_FEE,
    CASE WHEN H.END_DATE - H.START_DATE >= 90 THEN '90일 이상'
    WHEN H.END_DATE - H.START_DATE >= 30 THEN '30일 이상'
    WHEN H.END_DATE - H.START_DATE >= 7 THEN '7일 이상'
    ELSE '1일 이상' END DURATION_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H,
    CAR_RENTAL_COMPANY_CAR C
WHERE C.CAR_ID = H.CAR_ID) H 
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON P.CAR_TYPE = H.CAR_TYPE AND P.DURATION_TYPE = H.DURATION_TYPE
WHERE H.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC


