-- 코드를 입력하세요
SELECT M.MEMBER_NAME, R.REVIEW_TEXT, TO_CHAR(R.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM REST_REVIEW R, MEMBER_PROFILE M
WHERE M.MEMBER_ID = R.MEMBER_ID
AND R.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM (SELECT MEMBER_ID, DENSE_RANK() OVER (ORDER BY COUNT DESC) RK
          FROM (SELECT MEMBER_ID, COUNT(*) AS COUNT FROM REST_REVIEW GROUP BY MEMBER_ID))
    WHERE RK = 1)
ORDER BY REVIEW_DATE, REVIEW_TEXT