-- 코드를 입력하세요
SELECT EXTRACT(MONTH FROM START_DATE) MONTH, CAR_ID, COUNT(*) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE TO_CHAR(START_DATE, 'YYYYMMDD') BETWEEN '20220801' AND '20221031'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5)
AND TO_CHAR(START_DATE, 'YYYYMMDD') BETWEEN '20220801' AND '20221031'
GROUP BY EXTRACT(MONTH FROM START_DATE), CAR_ID
ORDER BY MONTH, CAR_ID DESC