-- 코드를 입력하세요
SELECT DISTINCT H.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C,
(SELECT * FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE EXTRACT(MONTH FROM START_DATE) = '10') H
WHERE C.CAR_ID = H.CAR_ID
AND C.CAR_TYPE = '세단'
ORDER BY CAR_ID DESC

